### ISSUE TITLE
Update fetch

### ISSUE THREAD

**Issue by Himasnhu-AT** [synthAI-Labs/WebClient-OpenEdu#22]
as per updates to Server's [#41](https://github.com/synthAI-Labs/server-OpenEdu/issues/41)

**Comment by Lymah123** [comment]
Hi @Himasnhu-AT , can I work on this issue?

**Comment by Himasnhu-AT** [comment]
Hi @Lymah123 ,
Right now all the fetch are according to api.
I'll update all of them by 10th of Jan, I.e. day after tomorrow. I'll ping you then with updated ones.

Is it okay with you?

**Comment by Lymah123** [comment]
> Hi @Lymah123 , Right now all the fetch are according to api. I'll update all of them by 10th of Jan, I.e. day after tomorrow. I'll ping you then with updated ones.
> 
> Is it okay with you?

Hi @Himasnhu-AT , yes. I am okay with it. Thank you.

**Comment by Himasnhu-AT** [comment]
Okay, I have updated most of api and here's a summary of it:
The only change is what server return:

Status: 403: error from user
Status: 404: request thing not found
Status: 500: server error

Here the return statement in case of an error:
```json
{
  "Status" :
  "message" : ""
}
```


You can take reference on how to update from `(auth)`.

Make sure to use toast to give message in description.

**Comment by Lymah123** [comment]
> Okay, I have updated most of api and here's a summary of it: The only change is what server return:
> 
> Status: 403: error from user Status: 404: request thing not found Status: 500: server error
> 
> Here the return statement in case of an error:
> 
> ```json
> {
>   "Status" :
>   "message" : ""
> }
> ```
> 
> You can take reference on how to update from `(auth)`.
> 
> Make sure to use toast to give message in description.

Hi @Himasnhu-AT , there's a national grid issue in my country for like 24 hrs now.  I will create a PR once I have been able to power my computer.

**Comment by Himasnhu-AT** [comment]
Okay that's great. Can it be complete by 11 EOD?

**Comment by Lymah123** [comment]
> Okay no worries. Can it be complete by 11 EOD?

Yes,  I will try to.

**Comment by Lymah123** [comment]
Once I'm done with this particular issue, I will be working on the second one too. So I can complete the tasks for my internship program.  I don't want to be looking for another repo to contribute to. Since I have one more task to complete after this particular one. Is it okay by you?

**Comment by Himasnhu-AT** [comment]
Okay that's great 👍

**Comment by Lymah123** [comment]
Thank you @Himasnhu-AT .

**Comment by Himasnhu-AT** [comment]
A minor improvement , when the api's will be updated, make sure it only calls the api one single time.
Right now its calling the api multiple times

**Comment by Lymah123** [comment]
> A minor improvement , when the api's will be updated, make sure it only calls the api one single time. Right now its calling the api multiple times

Hi @Himasnhu-AT , Alright.  I have heard you. 
I will work on it tomorrow and submit the PR in the night.  Sorry for delay from my end, I faced unforeseen circumstances.

**Comment by Himasnhu-AT** [comment]
That's okay. Take you time. Just wanted to update you on task.

**Comment by Lymah123** [comment]
> That's okay. Take you time. Just wanted to update you on task.

Hi @Himasnhu-AT , I will submit the PR tomorrow 12th.
Would that be okay with you?

**Comment by Himasnhu-AT** [comment]
> > That's okay. Take you time. Just wanted to update you on task.
> 
> Hi @Himasnhu-AT , I will submit the PR tomorrow 12th.
> Would that be okay with you?

Yes

**Comment by Lymah123** [comment]
Hi @Himasnhu-AT, can I hop on this?

**Comment by Himasnhu-AT** [comment]
> Okay, I have updated most of api and here's a summary of it:
> The only change is what server return:
> 
> Status: 403: error from user
> Status: 404: request thing not found
> Status: 500: server error
> 
> Here the return statement in case of an error:
> ```json
> {
>   "Status" :
>   "message" : ""
> }
> ```
> 
> 
> You can take reference on how to update from `(auth)`.
> 
> Make sure to use toast to give message in description. 
> 
>  

Is just like what u specified here. Update the call to server and handle response where Status is 403, 404, 500 using the toast

**Comment by Lymah123** [comment]
> > Okay, I have updated most of api and here's a summary of it:
> > The only change is what server return:
> > Status: 403: error from user
> > Status: 404: request thing not found
> > Status: 500: server error
> > Here the return statement in case of an error:
> > ```json
> > {
> >   "Status" :
> >   "message" : ""
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You can take reference on how to update from `(auth)`.
> > Make sure to use toast to give message in description.
> 
> Is just like what u specified here. Update the call to server and handle response where Status is 403, 404, 500 using the toast

![webedu](https://github.com/synthAI-Labs/WebClient-OpenEdu/assets/109049037/3369dd03-84f9-4e71-9ccd-1a7c5e6d836e)

@Himasnhu-AT , am I working only on this file?

**Comment by Lymah123** [comment]
> > Okay, I have updated most of api and here's a summary of it:
> > The only change is what server return:
> > Status: 403: error from user
> > Status: 404: request thing not found
> > Status: 500: server error
> > Here the return statement in case of an error:
> > ```json
> > {
> >   "Status" :
> >   "message" : ""
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You can take reference on how to update from `(auth)`.
> > Make sure to use toast to give message in description.
> 
> Is just like what u specified here. Update the call to server and handle response where Status is 403, 404, 500 using the toast

I should use `react-toastify` library,right? @Himasnhu-AT

**Comment by Himasnhu-AT** [comment]
> > > Okay, I have updated most of api and here's a summary of it:
> > > The only change is what server return:
> > > Status: 403: error from user
> > > Status: 404: request thing not found
> > > Status: 500: server error
> > > Here the return statement in case of an error:
> > > ```json
> > > {
> > >   "Status" :
> > >   "message" : ""
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > You can take reference on how to update from `(auth)`.
> > > Make sure to use toast to give message in description.
> > 
> > Is just like what u specified here. Update the call to server and handle response where Status is 403, 404, 500 using the toast
> 
> I should use `react-toastify` library,right? @Himasnhu-AT 

Nope, it's toast from components/ui/use-toast

**Comment by Himasnhu-AT** [comment]
> > > Okay, I have updated most of api and here's a summary of it:
> > > The only change is what server return:
> > > Status: 403: error from user
> > > Status: 404: request thing not found
> > > Status: 500: server error
> > > Here the return statement in case of an error:
> > > ```json
> > > {
> > >   "Status" :
> > >   "message" : ""
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > You can take reference on how to update from `(auth)`.
> > > Make sure to use toast to give message in description.
> > 
> > Is just like what u specified here. Update the call to server and handle response where Status is 403, 404, 500 using the toast
> 
> ![webedu](https://github.com/synthAI-Labs/WebClient-OpenEdu/assets/109049037/3369dd03-84f9-4e71-9ccd-1a7c5e6d836e)
> 
> @Himasnhu-AT , am I working only on this file?

Yes, just make sure the toast is shown. If it is not shown, try to modify return and make it work in page.tsx file
