### ISSUE TITLE
refactor code

### ISSUE THREAD

**Issue by Himasnhu-AT** [synthAI-Labs/WebClient-OpenEdu#23]

**Comment by Lymah123** [comment]
Hi @Himasnhu-AT , can I work on the issue?

**Comment by Himasnhu-AT** [comment]
Thank you for this. I'll assign it to you.
In refactoring,  I'm looking towards making code more modular.

**Comment by Himasnhu-AT** [comment]
I have made the commits, kindly update your for and run docker compose to setup server locally.

**Comment by Lymah123** [comment]
Hi @Himasnhu-AT, is it the docker file I am refactoring?

**Comment by Himasnhu-AT** [comment]
The nextjs app, this webclient one. Dockerfile is the server component and can come in handy while testing
