### ISSUE TITLE
 Implement jwt auth token and store it using cookie on frontend

### ISSUE THREAD

**Issue by rajeshj11** [synthAI-Labs/WebClient-OpenEdu#36]
server ticket: https://github.com/synthAI-Labs/server-OpenEdu/issues/42

**Comment by rajeshj11** [comment]
postman-api:
https://api.postman.com/collections/6631942-4c9d1ab3-33b9-450d-afff-7a7302377bda?access_key=PMAT-01HMD8C1E9G2NKY3DQV7EKVCQQ

**Comment by rajeshj11** [comment]
@Himasnhu-AT Please review
https://github.com/synthAI-Labs/WebClient-OpenEdu/pull/37

**Comment by Himasnhu-AT** [comment]
Thanks @rajeshj11
