### ISSUE TITLE
Redesign Layout of /learn/courses

### ISSUE THREAD

**Issue by Himasnhu-AT** [synthAI-Labs/WebClient-OpenEdu#6]
Revitalize the User Interface for the Learn Course Page

Elevate the visual appeal and layout of the Learn Course page for an enhanced user experience.

[Access Learn Course Page Here](https://web-client-ai-res.vercel.app/learn/courses)

<img width="641" alt="Screenshot 2023-12-28 at 3 50 42 PM" src="https://github.com/AI-RES/WebClient/assets/117301124/9bcacb83-4141-4a77-ba7d-7b0ca1e33623">

Objectives:
- Redesign the Learn Course page UI to optimize the learning journey.
- Improve the layout for a more organized and visually pleasing presentation.
- Optimize aesthetics to create an engaging and user-friendly interface for an enriched learning experience.

**Comment by Siddharth1605** [comment]
Hello @Himasnhu-AT , I would like to work on this feature, can you explain me how do you like your page to look?

**Comment by Himasnhu-AT** [comment]
Hi @Siddharth1605, Thank you for showing interest in this. 

### This is what I'm trying to make it look

 On top, header will have option to search through available courses based on name matching, and dropdown menu for filter based on tags.

> The search feature can be implemented later on

The course card will look something like this: 

<img width="329" alt="Screenshot 2023-12-31 at 1 14 41 PM" src="https://github.com/AI-RES/WebClient-OpenEdu/assets/117301124/b91f885f-e4b4-4fa3-9d2f-d728c9789f37">

## NOTE: You can add/remove sections to make the course look prettier. 

Also, for ease of building, try using shadcn-ui's  [Card component](https://ui.shadcn.com/docs/components/card) and [dropdown-menu component](https://ui.shadcn.com/docs/components/dropdown-menu) . 

> You can view other components too, if you think some other will look nice.

JSON RESPONSE EXAMPLE:

```json
[
  {
    "id": 1,
    "name": "Course 1",
    "description": "Description for Course 1",
    "image": "image.jpg",
    "userId": null,
    "tags": [
      "tag1",
      "tag2"
    ]
  },
  {
    "id": 2,
    "name": "Course 2",
    "description": "Description for Course 2",
    "image": "image.jpg",
    "userId": null,
    "tags": [
      "tag3",
      "tag4"
    ]
  }
]
```

**Comment by Himasnhu-AT** [comment]
Shall i assign you this issue?

**Comment by Siddharth1605** [comment]
Yeah sure,

**Comment by Himasnhu-AT** [comment]
hi @Siddharth1605 , status?
