### ISSUE TITLE
Redesign UI of learn/courses/1

### ISSUE THREAD

**Issue by Himasnhu-AT** [synthAI-Labs/WebClient-OpenEdu#7]
Revitalize the User Interface for the Learn Course Page

Elevate the visual appeal and layout of the Learn Course page for an enhanced user experience.

[Access Learn Course Page Here](https://web-client-ai-res.vercel.app/learn/courses/1)

<img width="787" alt="Screenshot 2023-12-28 at 3 52 41 PM" src="https://github.com/AI-RES/WebClient/assets/117301124/5b9efc95-d2af-432b-9fa5-415c776e21ec">

Objectives:
- Redesign the Learn Course page UI to optimize the learning journey.
- Improve the layout for a more organized and visually pleasing presentation.
- Optimize aesthetics to create an engaging and user-friendly interface for an enriched learning experience.

**Comment by Himasnhu-AT** [comment]
Hi @iSubhamMani , can you pick this up?

**Comment by iSubhamMani** [comment]
Yeah Sure
